More anime ig
thesilvercraft/SilverBot pull request #422
Opened 2021-12-10 11:15 UTC by Silverdimond

commits by @Wbubbler and stuff

2021-12-10 16:55 UTC, JMcB17 commented
👎

2021-12-11 12:07 UTC, JMcB17 requested changes
आपको अपने पापों के लिए पश्चाताप
करना चाहिए। वे तुम्हें नष्ट कर देंगे।
आप कोई मौका नहीं खड़े हैं। तुम
उसके हाथ पर मर जाओगे। पछताना

2021-12-31 11:06 UTC, Silverdimond commented
@Wbubbler the bots dont like your changes
![image](https://user-images.githubusercontent.com/46320280/147820032-7e94a556-6dc0-48e0-86ef-52369bb4a91a.png)

2022-01-21 20:42 UTC, Silverdimond commented
yeah i feel like i will fully remove the animemodule soon and i just do not like the concept of having hardcoded quotes in the bot

2022-01-21 20:42 UTC, closed without merging